### PR TITLE
Untested v4.8.0 Port

### PR DESCRIPTION
**Pull request by SunTheCourier**
One Player Private Battles is tested working

### CODE REVIEW

**Comment by 3096** [comment]
Then test it

**Comment by SunTheCourier** [comment]
no u

**Comment by SunTheCourier** [comment]
It was made with ur dumb find bytes smh

**Comment by OatmealDome** [comment]
Someone should test some at the very least (though it's a shame that running these will ban, so I suppose the number of people willing to is verylow)

**Comment by 3096** [comment]
Closing since it's not tested and no one is testing it.

**Pull request merged**
